require("plugins.colorscheme")
require("plugins.mini-icons")
require("plugins.treesitter")
require("plugins.neotree")
require("plugins.bufferline")
require("plugins.lualine")
require("plugins.blink_cmp")
require("plugins.mini-pairs")
