require("plugins.colorscheme")
require("plugins.mini")
require("plugins.dashboard")

vim.schedule(function()
  require("plugins.treesitter")
  require("plugins.neotree")
  require("plugins.bufferline")
  require("plugins.lualine")
  require("plugins.blink_cmp")
  require("plugins.fzf")
  require("plugins.which-key")
  require("plugins.conform")
end)
